name: KeepYourSession-CI

on: [push]

jobs:
  install:
    name: Install dependencies
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Display tools versions
        run: npm --version;

      - name: Restore all the packages
        run: npm ci

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}


  verify:
    name: Verify the sources
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Run ESLint on the sources
        run: npx eslint .\app\src\** .\__tests__\**


  test:
    name: Run the unit tests
    runs-on: windows-latest
    needs: [install, verify]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Pull the npm dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Run unit tests
        run: npx jest


  pre-build-package-verify:
    name: Verify the package before build
    runs-on: windows-latest
    needs: [install, verify]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Pull the npm dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Verify the package
        run: npx web-ext --source-dir "./app" lint


  build:
    name: Build the release package
    runs-on: windows-latest
    needs: [pre-build-package-verify]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Pull the npm dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Build the release package
        run: npx web-ext build --source-dir "./app" --ignore-files "__tests__"

      - name: Store the built package
        uses: actions/upload-artifact@v2
        with:
          name: release-candidate-package
          path: ./web-ext-artifacts/*
